"""知识用例实际使用的存储和外部服务端口；没有通用 CRUD 框架。"""

from __future__ import annotations
from collections.abc import Iterator
from contextlib import AbstractContextManager
from typing import Any, Protocol, TYPE_CHECKING
from app.modules.knowledge.domain.governance import SourceItem
from app.modules.knowledge.domain.models import KnowledgeJobAccess, OnesKnowledgeIdentity
from app.modules.knowledge.domain.normalization import PreparedRecord, PreparedExport
from app.modules.knowledge.domain.chunking import ChunkProfile, PreparedChunks
from app.modules.knowledge.domain.evaluation import EvaluationDataset
from app.modules.knowledge.application.retrieval_budget import RetrievalBudget

if TYPE_CHECKING:
    from app.modules.knowledge.application.readability import (
        ReadabilityCandidates,
        ReadabilityRequest,
    )


class GovernanceRepository(Protocol):
    def unit_of_work(self) -> AbstractContextManager[None]: ...
    def source_lock(self, source_id: str) -> AbstractContextManager[None]: ...
    def add(self, name: str, values: dict[str, Any]) -> None: ...
    def latest_source_revision(self, source_id: str) -> int: ...
    def revoke_source_bindings(self, source_id: str, actor_id: str, timestamp: str) -> None: ...
    def verify_binding(
        self, binding_id: str, digest: str, count: int, actor_id: str, job_id: str
    ) -> None: ...
    def revoke_binding(self, binding_id: str, actor_id: str) -> None: ...
    def members(self, base_id: str) -> list[dict[str, Any]]: ...
    def enabled_resources(self, base_id: str, *, excluding: str = "") -> list[dict[str, Any]]: ...
    def next_resource_revision(self, resource_id: str) -> int: ...
    def save_draft(self, resource_id: str, revision_id: str) -> None: ...
    def bump_resource_revision(self, resource_id: str) -> None: ...
    def verification(self, revision_id: str) -> dict[str, Any] | None: ...
    def publish(self, resource_id: str, revision_id: str, actor_id: str) -> None: ...
    def set_resource_status(self, resource_id: str, status: str) -> None: ...
    def current_documents(self, source_id: str, ids: tuple[str, ...]) -> dict[str, Any]: ...
    def source_catalog(self) -> dict[str, Any]: ...
    def catalog(self) -> dict[str, Any]: ...
    def resource_ids(self) -> list[str]: ...
    def published_resources_for_source(self, source_id: str) -> list[dict[str, Any]]: ...
    def get(self, name: str, identifier: str, *, lock: bool = False) -> dict[str, Any]: ...
    def source_items(self, source_id: str) -> tuple[SourceItem, ...]: ...
    def member_source_items(self, base_id: str, source_id: str) -> tuple[SourceItem, ...]: ...
    @staticmethod
    def source_hash(items: tuple[SourceItem, ...]) -> str: ...
    def assert_current_source(
        self,
        binding: dict[str, Any],
        *,
        instance_code: str,
        target_hash: str,
        verified: bool = True,
    ) -> tuple[SourceItem, ...]: ...


class ImportRepository(Protocol):
    def source_lock(self, source_id: str) -> AbstractContextManager[None]: ...
    def begin(
        self,
        prepared: PreparedExport,
        source_code: str,
        base_code: str,
        source_id: str,
        base_id: str,
        run_id: str,
        input_hash: str,
    ) -> dict[str, Any]: ...
    def verify(
        self, prepared: PreparedExport, *, source_id: str, base_id: str
    ) -> dict[str, int]: ...
    def commit_record(
        self, record: PreparedRecord, source_id: str, base_id: str, run_id: str
    ) -> None: ...
    def complete(self, source_id: str, run_id: str) -> None: ...
    def fail(self, run_id: str, code: str) -> None: ...
    def result(self, run_id: str) -> dict[str, Any]: ...


class SyncRepository(Protocol):
    def source_lock(self, source_id: str) -> AbstractContextManager[None]: ...
    def binding(self, binding_id: str) -> dict[str, Any]: ...
    def begin(self, binding_id: str, exports: tuple[PreparedExport, ...]) -> dict[str, Any]: ...
    def stage(self, run_id: str, record: PreparedRecord) -> str: ...
    def finish_staging(self, run_id: str) -> dict[str, Any]: ...
    def fail(self, run_id: str, code: str) -> None: ...
    def summary(self, run_id: str) -> dict[str, Any]: ...


class ChunkRepository(Protocol):
    profile: ChunkProfile

    def scope(self, code: str) -> tuple[str, str]: ...
    def rows(
        self, base_id: str, source_id: str, *, metadata_only: bool = False
    ) -> Iterator[dict[str, Any]]: ...
    def save(
        self, record: dict[str, Any], prepared: PreparedChunks, base_id: str, source_id: str
    ) -> str: ...
    def source_lock(self, source_id: str) -> AbstractContextManager[None]: ...
    def count(self, base_id: str, source_id: str) -> int: ...


class VectorRepository(Protocol):
    profile: dict[str, Any]

    def scope(self, code: str) -> str: ...
    def rows(self, base_id: str, chunk_profile: str) -> Iterator[dict[str, Any]]: ...
    def snapshot(
        self, base_id: str, chunk_profile: str, documents: int, chunks: int
    ) -> dict[str, Any]: ...
    def assert_current(self, index: dict[str, Any]) -> None: ...
    def get(self, code: str) -> dict[str, Any] | None: ...
    def reusable_rows(
        self, index: dict[str, Any], embedding_hashes: list[str]
    ) -> dict[str, dict[str, Any]]: ...
    def create(self, code: str, snapshot: dict[str, Any]) -> dict[str, Any]: ...
    def manifest(self, index: dict[str, Any]) -> None: ...
    def state(self, index: dict[str, Any], state: str, error: str | None = None) -> None: ...
    def checkpoint(
        self,
        index: dict[str, Any],
        rows: list[dict[str, Any]],
        state: str,
        *,
        error: str | None = None,
        attempted: bool = False,
    ) -> None: ...
    def evidence_many(
        self, index: dict[str, Any], chunk_ids: list[str]
    ) -> dict[str, dict[str, Any]]: ...
    def evaluation_catalog(
        self, dataset: EvaluationDataset, index: dict[str, Any]
    ) -> dict[str, str]: ...
    def source_lock(self, source_id: str) -> AbstractContextManager[None]: ...
    @staticmethod
    def implementation_hash() -> str: ...


class SourceTechnicalVerifier(Protocol):
    """由固定 ONES 适配器提供；客户端不能提交此对象或技术核验结果。"""

    instance_code: str
    target_hash: str

    def verify(
        self,
        *,
        actor_id: str,
        job_id: str,
        binding_id: str,
        team_id: str,
        items: tuple[SourceItem, ...],
    ) -> bool: ...


class EmbeddingPort(Protocol):
    profile: dict[str, Any]
    profile_hash: str

    def check(self) -> None: ...
    def call(self, texts: list[str], *, encode: bool = False) -> dict[str, Any]: ...


class QdrantPort(Protocol):
    def hybrid_search(
        self,
        index: dict[str, Any],
        vector: list[float] | None,
        text: str,
        limit: int,
        *,
        mode: str = "hybrid",
    ) -> list[dict[str, Any]]: ...
    def check(self, index: dict[str, Any]) -> None: ...
    def count(self, index: dict[str, Any]) -> int: ...
    def ensure(self, index: dict[str, Any]) -> None: ...
    def search(
        self, index: dict[str, Any], vector: list[float], limit: int
    ) -> list[dict[str, Any]]: ...
    def retrieve(self, index: dict[str, Any], ids: list[str]) -> dict[str, Any]: ...
    def upsert(self, index: dict[str, Any], points: list[dict[str, Any]]) -> None: ...
    def delete_owned(self, index: dict[str, Any]) -> None: ...


class GenerationRepository(Protocol):
    def candidates(self) -> Iterator[dict[str, Any]]: ...
    def source_lock(self, source_id: str) -> AbstractContextManager[None]: ...
    def eligible(self, index_id: str, timestamp: str) -> dict[str, Any] | None: ...
    def retired(self, index_id: str) -> None: ...


class PrincipalAccess(Protocol):
    def authenticate(self, token: str, tool: str) -> KnowledgeJobAccess: ...
    def identity(self, actor_id: str) -> OnesKnowledgeIdentity: ...
    def budget(self, job_id: str, *, deadline_ms: int | None = None) -> RetrievalBudget: ...


class ReadabilityPort(Protocol):
    def check(self, *, token: str, request: ReadabilityRequest) -> dict[str, Any]: ...


class ReadabilityBridgeGateway(Protocol):
    def authenticate(self, service_token: str, knowledge_token: str) -> KnowledgeJobAccess: ...
    def budget(self, job_id: str, *, deadline_ms: int | None = None) -> RetrievalBudget: ...
    def identity_fingerprint(self, actor_id: str, candidates: ReadabilityCandidates) -> str: ...
    def request_ones(self, job_id: str, request: ReadabilityRequest) -> Any: ...
