# Generated by agent-runtime/scripts/generate-contracts.mjs. Do not edit.
from __future__ import annotations

import json
from pathlib import Path
from typing import Literal, NotRequired, TypedDict

from jsonschema import Draft202012Validator

PROTOCOL_VERSION = "1.0"
CONTRACT_SCHEMA_SHA256 = "30a3e6f2fb733b63d057e01e589c7c5dbc8224d4c28992a13b0cdfb6014a1397"
CONTRACT_SCHEMA_PATH = (
    Path(__file__).resolve().parents[5]
    / "agent-runtime"
    / "contracts"
    / "v1"
    / "protocol.schema.json"
)

Identifier = str
Sha256Digest = str
RuntimeKind = Literal["python-v1", "typescript-v1"]
SafeMessage = str
RuntimeEvent = dict[str, object] | dict[str, object] | dict[str, object] | dict[str, object]

class JsonSummary(TypedDict):
    pass


class ExecutionLimits(TypedDict):
    timeout_seconds: int
    max_turns: int
    max_tool_calls: int


class Prompt(TypedDict):
    system_role: str
    safety_rules: list[str]
    business_instructions: str
    tool_restrictions: list[str]
    user_question: str
    conversation_summary: str
    retrieved_context: dict[str, object]
    skills: NotRequired[dict[str, str]]
    mcp_unavailable_notices: NotRequired[list[dict[str, object]]]


class ModelConnectionBinding(TypedDict):
    revision_id: Identifier
    config_hash: Sha256Digest


class ModelProbeRequest(TypedDict):
    protocol_version: Literal["1.0"]
    runtime_kind: RuntimeKind
    probe_id: Identifier
    model_connection: ModelConnectionBinding
    timeout_seconds: int


class ModelProbeCredentialEnvelope(TypedDict):
    algorithm: Literal["AES-256-GCM-DERIVED-PROBE-V1"]
    nonce: str
    ciphertext: str
    expires_at: int


class DraftModelProbeRequest(TypedDict):
    protocol_version: Literal["1.0"]
    runtime_kind: RuntimeKind
    probe_id: Identifier
    config_hash: Sha256Digest
    credential_envelope: ModelProbeCredentialEnvelope
    timeout_seconds: int


class ModelProbeFailure(TypedDict):
    code: Identifier
    safe_message: SafeMessage


class ModelProbeResponse(TypedDict):
    protocol_version: Literal["1.0"]
    runtime_kind: RuntimeKind
    probe_id: Identifier
    success: bool
    connection_revision_id: Identifier
    provider_host: str
    model: str
    runtime_version: str
    sdk_version: str
    duration_ms: int
    failure: NotRequired[ModelProbeFailure]


class McpToolBinding(TypedDict):
    tool_name: Identifier
    required_scope: Identifier
    tool_schema_hash: Sha256Digest
    resource_code: NotRequired[Identifier]
    resource_deployment_id: NotRequired[Identifier]
    resource_revision_id: NotRequired[Identifier]


class McpServerBinding(TypedDict):
    server_code: Literal["tool-mcp", "ones-mcp"]
    tools: list[McpToolBinding]


class AgentExecutionRequestV1(TypedDict):
    protocol_version: Literal["1.0"]
    runtime_kind: RuntimeKind
    invocation_id: Identifier
    request_digest: Sha256Digest
    job_id: Identifier
    app_user_id: Identifier
    project_code: Identifier
    agent_publication_id: Identifier
    application_publication_id: Identifier
    model_connection: ModelConnectionBinding
    prompt: Prompt
    limits: ExecutionLimits
    mcp_servers: list[McpServerBinding]


class RuntimeGrantClaims(TypedDict):
    iss: Literal["enterprise-agent-worker"]
    aud: Literal["agent-runtime"]
    azp: Literal["agent-worker"]
    runtime_kind: RuntimeKind
    sub: Identifier
    job_id: Identifier
    invocation_id: Identifier
    agent_publication_id: Identifier
    application_publication_id: Identifier
    request_digest: Sha256Digest
    iat: int
    nbf: int
    exp: int
    jti: Identifier


class Usage(TypedDict):
    input_tokens: int
    output_tokens: int
    cache_read_input_tokens: NotRequired[int]
    cache_creation_input_tokens: NotRequired[int]


class RuntimeProvenance(TypedDict):
    runtime_kind: RuntimeKind
    runtime_version: str
    protocol_version: Literal["1.0"]
    sdk_version: str
    cli_version: str
    model_connection_revision_id: Identifier
    model_connection_config_hash: Sha256Digest


class RuntimeFailure(TypedDict):
    code: Identifier
    retry_class: Literal["NEVER", "TRANSIENT", "CONFIGURATION"]
    safe_message: SafeMessage


class ToolEvent(TypedDict):
    tool_call_id: Identifier
    server_code: Literal["tool-mcp", "ones-mcp"]
    tool_name: Identifier
    status: Literal["STARTED", "SUCCEEDED", "FAILED", "DENIED"]
    request_summary: JsonSummary
    response_summary: JsonSummary
    duration_ms: int
    failure: NotRequired[RuntimeFailure]


class TerminalResult(TypedDict):
    protocol_version: Literal["1.0"]
    invocation_id: Identifier
    request_digest: Sha256Digest
    last_sequence: int
    status: Literal["SUCCEEDED", "FAILED", "CANCELLED"]
    final_answer: NotRequired[str]
    failure: NotRequired[RuntimeFailure]
    usage: Usage
    runtime_provenance: RuntimeProvenance


class CancelRequest(TypedDict):
    protocol_version: Literal["1.0"]
    invocation_id: Identifier
    request_digest: Sha256Digest
    reason: Literal["JOB_CANCELLED", "WORKER_TIMEOUT", "CLIENT_DISCONNECTED", "WORKER_SHUTDOWN"]


def validate_contract(definition_name: str, payload: object) -> None:
    schema = json.loads(CONTRACT_SCHEMA_PATH.read_text(encoding="utf-8"))
    definition = schema.get("$defs", {}).get(definition_name)
    if definition is None:
        raise ValueError(f"unknown runtime contract: {definition_name}")
    validator = Draft202012Validator(
        {"$ref": f"#/$defs/{definition_name}", "$defs": schema["$defs"]}
    )
    errors = sorted(validator.iter_errors(payload), key=lambda item: list(item.path))
    if errors:
        detail = "; ".join(error.message for error in errors[:8])
        raise ValueError(f"invalid {definition_name}: {detail}")
