"""Shared numeric quotas for the existing sandbox-v2 policy (no protocol bump)."""

SANDBOX_LIMIT_VERSION = "sandbox-v2"
SANDBOX_FILE_LIMIT = 128
SANDBOX_CAPACITY_BYTES = 512 * 1024 * 1024
SANDBOX_FILE_BYTES = 15 * 1024 * 1024
SANDBOX_INPUT_FILE_LIMIT = 40
SANDBOX_WORK_OUTPUT_FILE_LIMIT = 80
SANDBOX_TMP_FILE_LIMIT = 8
