import { useState, type ReactNode } from "react";
import { Activity, AlertTriangle, Bot, Cable, ChevronLeft, ChevronRight, Clock3, Search, UsersRound } from "lucide-react";
import { Badge } from "@enterprise-agent/ui/components/badge";
import { Button } from "@enterprise-agent/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@enterprise-agent/ui/components/card";
import { Input } from "@enterprise-agent/ui/components/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@enterprise-agent/ui/components/sheet";
import { Skeleton } from "@enterprise-agent/ui/components/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@enterprise-agent/ui/components/table";
import { useAttachment, useAttachments, useConversation, useConversations, useDashboard, useJob, useJobs, useQueues } from "../application/queries";
import type { QueueSnapshot } from "../domain/models";

const date = (value?: string) => value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "short", timeStyle: "medium" }).format(new Date(value)) : "—";
const windowAt = (hours:number) => ({start:new Date(Date.now()-hours*3_600_000).toISOString(),end:new Date().toISOString()});

export function DashboardPage() {
  const [window,setWindow]=useState(()=>windowAt(24));
  const query = useDashboard(window);
  if (query.isLoading) return <LoadingCards />;
  if (query.isError || !query.data) return <State title="无法读取 Dashboard" detail="请重试；错误详情已使用 correlation id 记录。" action={<Button variant="outline" onClick={()=>query.refetch()}>重试</Button>}/>;
  const data = query.data;
  const cards = [
    ["统一用户", data.summary.users, UsersRound, "当前授权范围"],
    ["启用 Agent", data.summary.agents, Bot, "MVP 仅编辑默认 Agent"],
    ["Channel", data.summary.channels, Cable, "可用入口与投递"],
    ["窗口内任务", data.summary.jobs, Activity, `${data.summary.exceptions} 个异常`],
  ] as const;
  return <div className="space-y-6">
    <PageHeading eyebrow="Operations overview" title="运行态势" description="权限裁剪后的任务、投递、队列与入口活动。页面刷新不会连接业务数据库、Redis、Loki 或钉钉。" meta={`生成于 ${date(data.generated_at)}`} actions={<select className="input w-32" aria-label="统计时间窗口" onChange={e=>setWindow(windowAt(Number(e.target.value)))} defaultValue="24"><option value="6">最近 6 小时</option><option value="24">最近 24 小时</option><option value="72">最近 3 天</option></select>}/>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, help]) => <Card key={label} className="metric-card"><CardHeader className="flex-row items-start justify-between"><div><CardDescription>{label}</CardDescription><CardTitle className="mt-2 text-3xl">{value}</CardTitle></div><span className="metric-icon"><Icon size={18}/></span></CardHeader><CardContent className="text-xs text-muted-foreground">{help}</CardContent></Card>)}</div>
    <div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
      <Card><CardHeader><CardTitle>任务状态</CardTitle><CardDescription>{date(data.window.start)} — {date(data.window.end)}</CardDescription></CardHeader><CardContent><div className="status-bars">{Object.entries(data.jobs.counts).map(([status, count]) => <div key={status}><span>{status}</span><div><i style={{ width: `${Math.max(4, Math.min(100, count * 12))}%` }}/></div><strong>{count}</strong></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle size={17}/>异常摘要</CardTitle></CardHeader><CardContent className="space-y-3"><StatRow label="失败" value={data.jobs.failed}/><StatRow label="超时" value={data.jobs.timeout}/><StatRow label="等待重试" value={data.jobs.retry_wait}/><StatRow label="投递失败" value={data.jobs.delivery_failed}/></CardContent></Card>
    </div>
    <div className="grid gap-4 xl:grid-cols-2"><QueueCard data={data.queues}/><Card><CardHeader><CardTitle>最近会话</CardTitle><CardDescription>已按内部用户与平台范围过滤</CardDescription></CardHeader><CardContent><CompactTable headers={["Channel", "会话", "更新时间"]} rows={data.recent_conversations.map(item => [item.source_channel, item.external_conversation_id || item.id, date(item.updated_at)])}/></CardContent></Card></div>
  </div>;
}

export function QueuesPage() {
  const query = useQueues();
  return <div className="space-y-6"><PageHeading eyebrow="Read-only operations" title="队列状态" description="仅展示 allowlist 中的主队列、延迟重试和死信关系；不提供清空、删除、发布或重放。" meta={query.data?`采集于 ${date(query.data.collected_at)}`:undefined}/>{query.isError?<State title="队列指标暂不可用" detail="RabbitMQ 管理端失败不会影响其他管理模块。" action={<Button variant="outline" onClick={()=>query.refetch()}>重试</Button>}/>:query.data?<QueueCard data={query.data} expanded/>:<LoadingCards/>}</div>;
}

export function JobsPage(){
  const [status,setStatus]=useState("");
  const [correlation,setCorrelation]=useState("");
  const [selected,setSelected]=useState("");
  const [cursors,setCursors]=useState<string[]>([""]);
  const query=useJobs({status,correlation_id:correlation,cursor:cursors.at(-1)||undefined});
  const detail=useJob(selected);
  return <div className="space-y-6"><PageHeading eyebrow="End-to-end evidence" title="Job 与 Delivery" description="从入口事件、重试、工具调用追踪到最终投递；只展示安全摘要。"/><FilterBar><select className="input" aria-label="任务状态" value={status} onChange={e=>{setStatus(e.target.value);setCursors([""]);}}><option value="">全部状态</option>{["PENDING","RUNNING","RETRY_WAIT","SUCCEEDED","FAILED","TIMED_OUT"].map(v=><option key={v}>{v}</option>)}</select><Input aria-label="Correlation ID" placeholder="Correlation ID" value={correlation} onChange={e=>{setCorrelation(e.target.value);setCursors([""]);}}/></FilterBar><Card><CardContent className="pt-6"><Table><TableHeader><TableRow><TableHead>Job</TableHead><TableHead>状态</TableHead><TableHead>Agent / Channel</TableHead><TableHead>时间</TableHead></TableRow></TableHeader><TableBody>{(query.data?.items??[]).map(item=><TableRow className="cursor-pointer" key={item.id} onClick={()=>setSelected(item.id)}><TableCell className="font-mono text-xs">{item.id}</TableCell><TableCell><Badge variant="outline">{item.status}</Badge></TableCell><TableCell>{item.project_code} · {item.source_channel}</TableCell><TableCell>{date(item.created_at)}</TableCell></TableRow>)}</TableBody></Table>{!query.isLoading&&!query.data?.items.length?<State title="暂无任务" detail="当前时间窗口和筛选条件内没有任务。"/>:null}<CursorPagination page={query.data?.page} hasPrevious={cursors.length>1} onPrevious={()=>setCursors(current=>current.slice(0,-1))} onNext={(cursor)=>setCursors(current=>[...current,cursor])}/></CardContent></Card><DetailSheet open={Boolean(selected)} title={detail.data?.job.id??"任务详情"} description="Webhook → Job → Retry/Tool → Delivery" onClose={()=>setSelected("")}>{detail.isLoading?<LoadingCards/>:detail.data?<JobTimeline data={detail.data}/>:<State title="无法读取任务详情" detail="任务可能已超出授权范围。"/>}</DetailSheet></div>;
}

export function ConversationsPage() {
  const [channel,setChannel]=useState(""); const [external,setExternal]=useState(""); const [selected,setSelected]=useState(""); const [cursors,setCursors]=useState<string[]>([""]);
  const query=useConversations({channel,external_conversation_id:external,cursor:cursors.at(-1)||undefined}); const detail=useConversation(selected); const items=query.data?.items??[];
  return <div className="space-y-6"><PageHeading eyebrow="Conversation history" title="历史对话" description="从入口会话追踪消息、Agent Job、工具证据、附件和最终投递。"/><FilterBar><Input aria-label="Channel" placeholder="Channel" value={channel} onChange={e=>{setChannel(e.target.value);setCursors([""]);}}/><Input aria-label="外部会话 ID" placeholder="外部会话 ID" value={external} onChange={e=>{setExternal(e.target.value);setCursors([""]);}}/></FilterBar><Card><CardContent className="pt-6"><Table><TableHeader><TableRow><TableHead>请求人</TableHead><TableHead>Channel</TableHead><TableHead>外部会话</TableHead><TableHead>任务</TableHead><TableHead>更新时间</TableHead></TableRow></TableHeader><TableBody>{items.map(item => <TableRow className="cursor-pointer" key={item.id} onClick={()=>setSelected(item.id)}><TableCell className="font-medium">{item.requester_display_name || item.requester_id}</TableCell><TableCell><Badge variant="outline">{item.source_channel}</Badge></TableCell><TableCell className="font-mono text-xs">{item.external_conversation_id || item.id}</TableCell><TableCell>{item.job_count ?? 0} · {item.latest_job_status || "—"}</TableCell><TableCell>{date(item.updated_at)}</TableCell></TableRow>)}</TableBody></Table>{!query.isLoading && !items.length ? <State title="暂无会话" detail="当前时间窗口和权限范围内没有记录。"/> : null}<CursorPagination page={query.data?.page} hasPrevious={cursors.length>1} onPrevious={()=>setCursors(current=>current.slice(0,-1))} onNext={(cursor)=>setCursors(current=>[...current,cursor])}/></CardContent></Card><DetailSheet open={Boolean(selected)} title="会话时间线" description={detail.data?.session.external_conversation_id||selected} onClose={()=>setSelected("")}>{detail.data?<ConversationTimeline data={detail.data}/>:detail.isLoading?<LoadingCards/>:<State title="无法读取会话" detail="会话可能已超出授权范围。"/>}</DetailSheet></div>;
}

export function AttachmentsPage() {
  const [mime,setMime]=useState(""); const [status,setStatus]=useState(""); const [selected,setSelected]=useState(""); const [cursors,setCursors]=useState<string[]>([""]);
  const query=useAttachments({mime,status,cursor:cursors.at(-1)||undefined}); const detail=useAttachment(selected); const items=query.data?.items??[];
  return <div className="space-y-6"><PageHeading eyebrow="Safe metadata" title="附件" description="只读展示已存在的元数据与文本预览；不会启动暂停中的 Office/Markdown 提取链路。"/><FilterBar><Input aria-label="MIME 类型" placeholder="MIME 类型" value={mime} onChange={e=>{setMime(e.target.value);setCursors([""]);}}/><Input aria-label="处理状态" placeholder="处理状态" value={status} onChange={e=>{setStatus(e.target.value);setCursors([""]);}}/></FilterBar><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item => <Card className="cursor-pointer" key={item.id} onClick={()=>setSelected(item.id)}><CardHeader><div className="flex items-center justify-between"><span className="file-kicker">{item.detected_mime || item.declared_mime || "FILE"}</span><Badge variant="outline">{item.status}</Badge></div><CardTitle className="truncate text-base">{item.file_name}</CardTitle><CardDescription>{item.size_bytes ? `${Math.ceil(item.size_bytes/1024)} KB` : "大小未知"} · {date(item.created_at)}</CardDescription></CardHeader><CardContent><p className="line-clamp-3 text-sm text-muted-foreground">{item.text_preview || "尚无安全文本预览"}</p></CardContent></Card>)}</div>{!query.isLoading && !items.length ? <State title="暂无附件" detail="当前时间窗口和权限范围内没有附件。"/> : null}<CursorPagination page={query.data?.page} hasPrevious={cursors.length>1} onPrevious={()=>setCursors(current=>current.slice(0,-1))} onNext={(cursor)=>setCursors(current=>[...current,cursor])}/><DetailSheet open={Boolean(selected)} title={detail.data?.attachment.file_name??"附件详情"} description="安全元数据与现有文本预览" onClose={()=>setSelected("")}>{detail.data?<div className="space-y-4"><Badge variant="outline">{detail.data.attachment.status}</Badge><p className="whitespace-pre-wrap text-sm">{detail.data.attachment.text_preview||"暂无文本预览"}</p><div className="safety-callout"><AlertTriangle/><p>对象存储位置已隐藏；页面不生成永久下载 URL，也不触发文本提取。</p></div></div>:detail.isLoading?<LoadingCards/>:<State title="无法读取附件" detail="附件可能已超出授权范围。"/>}</DetailSheet></div>;
}

function JobTimeline({data}:{data:import("../domain/models").JobDetail}){return <div className="timeline"><TimelineItem title={`Job ${data.job.status}`} meta={`${date(data.job.created_at)} · retry ${data.retry.count}/${data.retry.max}`} body={data.job.error_summary}/>{data.webhook_events.map((item,index)=><TimelineItem key={`w${index}`} title={`Webhook ${String(item.status??"")}`} meta={String(item.correlation_id??"")} body={String(item.error_summary??"")}/>) }{data.steps.map((item,index)=><TimelineItem key={`s${index}`} title={String(item.title??item.step_type??"Step")} meta={date(String(item.created_at??""))} body={String(item.content??"")}/>) }{data.tool_calls.map((item,index)=><TimelineItem key={`t${index}`} title={`Tool · ${String(item.tool_name??"")}`} meta={`${String(item.status??"")} · ${String(item.duration_ms??0)}ms`} body={String(item.response_summary??"")}/>) }{data.delivery_attempts.map((item,index)=><TimelineItem key={`d${index}`} title={`Delivery · ${String(item.status??"")}`} meta={`${String(item.route_type??"")} · ${String(item.connector_id??"")}`} body={String(item.error_summary??"")}/>)}</div>}
function ConversationTimeline({data}:{data:import("../domain/models").ConversationDetail}){return <div className="timeline">{data.messages.map(item=><TimelineItem key={item.id} title={`${item.role} · ${item.message_type}`} meta={date(item.created_at)} body={item.content}/>)}{data.jobs.map(item=><TimelineItem key={item.id} title={`Job · ${item.status}`} meta={date(item.created_at)} body={item.error_summary}/>)}</div>}
function TimelineItem({title,meta,body}:{title:string;meta:string;body?:string}){return <div className="timeline-item"><i/><div><strong>{title}</strong><span>{meta}</span>{body?<p>{body}</p>:null}</div></div>}
function DetailSheet({open,title,description,onClose,children}:{open:boolean;title:string;description:string;onClose:()=>void;children:ReactNode}){return <Sheet open={open} onOpenChange={value=>{if(!value)onClose();}}><SheetContent className="overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>{title}</SheetTitle><SheetDescription>{description}</SheetDescription></SheetHeader><div className="p-4">{children}</div></SheetContent></Sheet>}
function FilterBar({children}:{children:ReactNode}){return <Card><CardContent className="flex flex-wrap items-center gap-3 py-4"><Search size={16} className="text-muted-foreground"/>{children}</CardContent></Card>}
function CursorPagination({page,hasPrevious,onPrevious,onNext}:{page?:{limit:number;has_more:boolean;next_cursor:string|null};hasPrevious:boolean;onPrevious:()=>void;onNext:(cursor:string)=>void}){if(!page||(!hasPrevious&&!page.has_more))return null;return <div className="mt-4 flex items-center justify-end gap-2 border-t pt-4"><span className="mr-2 text-xs text-muted-foreground">每页最多 {page.limit} 条</span><Button size="sm" variant="outline" disabled={!hasPrevious} onClick={onPrevious}><ChevronLeft/>上一页</Button><Button size="sm" variant="outline" disabled={!page.has_more||!page.next_cursor} onClick={()=>page.next_cursor&&onNext(page.next_cursor)}>下一页<ChevronRight/></Button></div>}
function QueueCard({ data, expanded=false }: { data: QueueSnapshot; expanded?: boolean }) { return <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>RabbitMQ</CardTitle><CardDescription>采集于 {date(data.collected_at)}</CardDescription></div><Badge variant={data.availability === "available" ? "secondary" : "destructive"}>{data.availability}</Badge></div></CardHeader><CardContent>{data.availability === "unavailable" ? <State title="队列指标暂不可用" detail={data.error?.message || "其他区域仍可正常使用。"}/> : <CompactTable headers={["队列", "用途", "Ready / Unacked", "消费者", "关系"]} rows={data.items.slice(0, expanded ? 20 : 5).map(item => [item.name,item.purpose, `${item.ready ?? "—"} / ${item.unacked ?? "—"}`, String(item.consumers ?? "—"),item.retry_of?`retry of ${item.retry_of}`:item.dead_letter_of?`DLQ of ${item.dead_letter_of}`:"—"])}/>}</CardContent></Card>; }
function StatRow({ label, value }: { label: string; value: number }) { return <div className="flex items-center justify-between rounded-lg border px-3 py-2"><span className="text-sm text-muted-foreground">{label}</span><strong>{value}</strong></div>; }
function CompactTable({ headers, rows }: { headers: string[]; rows: string[][] }) { return <Table><TableHeader><TableRow>{headers.map(h => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((cell,j)=><TableCell key={j} className={j===0?"font-medium":""}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table>; }
function LoadingCards() { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({length:4},(_,i)=><Skeleton key={i} className="h-36 rounded-xl"/>)}</div>; }
function State({ title, detail, action }: { title: string; detail: string; action?:ReactNode }) { return <div className="empty-panel"><Clock3/><strong>{title}</strong><p>{detail}</p>{action}</div>; }
export function PageHeading({ eyebrow, title, description, meta, actions }: { eyebrow: string; title: string; description: string; meta?: string; actions?:ReactNode }) { return <header className="page-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="flex items-center gap-3">{actions}{meta ? <small>{meta}</small> : null}</div></header>; }
