{
  buckets(groupBy: $groupBy, orderBy: $groupOrderBy, pagination: $pagination, filter: $groupFilter) {
    tasks(filterGroup: $filterGroup, orderBy: $orderBy) {
      uuid
      number
      name
      serverUpdateStamp
      createTime
      subTaskCount
      subTaskDoneCount
      issueType { uuid }
      project { uuid name }
      status { uuid name category }
      owner { uuid name }
      assign { uuid name }
      sprint { uuid name }
    }
    pageInfo { count totalCount endCursor hasNextPage unstable }
  }
}
